export const dataGenEd = {
  "2100111": {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "2100111",
    "abbrName": "EXPL ENG WORLD",
    "courseNameTh": "ท่องโลกวิศวกรรม",
    "courseNameEn": "EXPLORING ENGINEERING WORLD",
    "faculty": "21",
    "department": "ไม่สังกัดภาควิชา/เทียบเท่า",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "หัวข้อทางวิศวกรรมที่เกี่ยวข้องกับชีวิตประจำวัน ได้แก่ พลังงาน ทรัพยากร สิ่งแวดล้อม การผลิต กระบวนการอุตสาหกรรม วัสดุ ยานยนต์ โครงสร้างพื้นฐาน ระบบสารสนเทศ และวิศวกรรมชีวภาพ",
    "courseDescEn":
      "Engineering topics related to daily life: energy, resources, environment manufacturing, process, industry, material, automotive, infrastructure, information system and bio engineering",
    "genEdType": "SC",
    "__typename": "Course",
    "dropbox": "",
  },
  "2313213": {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "2313213",
    "abbrName": "DIGITAL PHOTO",
    "courseNameTh": "การถ่ายภาพดิจิทัล",
    "courseNameEn": "DIGITAL PHOTOGRAPHY",
    "faculty": "23",
    "department": "ภาควิชาเทคโนโลยีทางภาพและการพิมพ์",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "ประเภทของกล้องดิจิทัล องค์ประกอบพื้นฐานของกล้องดิจิทัล ขนาดของภาพและประเภทของไฟล์ภาพ การปรับตั้งค่าในการถ่ายภาพ การควบคุมการเปิดรับแสง การจัดองค์ประกอบ เทคนิคการถ่ายภาพแบบต่างๆ การตกแต่งภาพ เทคนิคการนำเสนอภาพ",
    "courseDescEn":
      "Types of digital camera; basic elements of digital camera; image size and file type; photographic setting; exposure control; composition; various types of photographic techniques; image editing; image presentation techniques.",
    "genEdType": "SC",
    "__typename": "Course",
    "dropbox": "",
  },
  "3700110": {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "3700110",
    "abbrName": "GOOD HEALTH",
    "courseNameTh": "สุขภาวะที่ดี",
    "courseNameEn": "GOOD HEALTH",
    "faculty": "37",
    "department": "ไม่สังกัดภาควิชา/เทียบเท่า",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "บทนำเกี่ยวกับการทำงานของระบบร่างกาย ความผิดปกติในการทำงานของระบบร่างกายอันเนื่องมาจากปัจจัยต่างๆ การตรวจสุขภาพประจำปี การเตรียมตัวและขั้นตอนปฏิบัติในการตรวจสุขภาพในด้านต่างๆ ได้แก่ การตรวจร่างกายเบื้องต้น และการตรวจทางห้องปฏิบัติการ การตรวจวัดการทำงานของปอดและหัวใจ การตรวจมะเร็งและสารบ่งชี้มะเร็ง การตรวจสุขภาพสำหรับคู่บ่าวสาว การดูแลสุขภาพกายและจิตด้วยตนเอง การเตรียมตัวเพื่อการตรวจร่างกายด้วยเครื่องมือพิเศษ โรคภัยในเด็ก วัยรุ่น สตรี และผู้สูงวัย ข้อแนะนำในการปฏิบัติตนเมื่อตรวจพบความผิดปกติ และข้อควรปฏิบัติในการดูแลและป้องกันตนเองเพื่อหลีกเลี่ยงความผิดปกติของการทำงานของระบบร่างกาย การศึกษาดูงานห้องปฏิบัติการการตรวจสุขภาพ และการเข้าร่วมกิจกรรมหรือการรณรงค์เพื่อสุขภาพ",
    "courseDescEn":
      "Introduction to organ system functions, organ dysfunctions due to several factors; annual health check-up, preparations and process of health check-up including physical examination and laboratory examination; heart and lung examination, cancer examination and tumor marker detection, health tests for couples, self health care for body and mind; preparations for health check-up using special instruments; diseases in children, teenagers, women and elderly; health prevention for better organ system functions; observation of a clinical laboratory for health check-up and participation of health care activity or campaign.",
    "genEdType": "SC",
    "__typename": "Course",
    "dropbox": "",
  },
  "2313221": {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "2313221",
    "abbrName": "PHOTO SCI",
    "courseNameTh": "วิทยาศาสตร์การถ่ายภาพ",
    "courseNameEn": "PHOTOGRAPHIC SCIENCE",
    "faculty": "23",
    "department": "ภาควิชาเทคโนโลยีทางภาพและการพิมพ์",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "แหล่งกำเนิดแสง อุณหภูมิสี พื้นฐานการมองเห็นสี กล้องถ่ายภาพและเทคนิคการใช้ ประเภทของกล้องถ่ายภาพ เลนส์และอุปกรณ์เสริม ทฤษฎีการเกิดภาพ วัสดุไวแสง กระบวนการสร้างภาพ ลักษณะเฉพาะและการวัดความไวของวัสดุไวแสง การอัดขยายภาพ เทคนิคการถ่ายภาพ",
    "courseDescEn":
      "Light sources; color temperature; basic color vision; camera structures and usage; types of cameras; lens and accessories; theory of image formation; photosensitive media; photographic processes; characteristic curves and photographic sensitometry; photographic printing; photographic techniques.",
    "genEdType": "SC",
    "__typename": "Course",
    "dropbox": "",
  },
  "3741329": {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "3741329",
    "abbrName": "PATIENT SAFETY",
    "courseNameTh": "ความปลอดภัยของผู้ป่วย",
    "courseNameEn": "PATIENT SAFETY",
    "faculty": "37",
    "department": "สาขาวิชาเทคนิคการแพทย์",
    "credit": 1,
    "creditHours": "LECT 1.0 CR(LECT 1.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "ความหมายของความปลอดภัยของผู้ป่วย นโยบายและเป้าหมายด้านความปลอดภัยของผู้ป่วยระดับโลกและระดับประเทศ ปัจจัยด้านมนุษย์ที่มีความสำคัญต่อความปลอดภัยของผู้ป่วย ความร่วมมือของทีมสหวิชาชีพในการดูแลรักษาผู้ป่วย วิธีปฏิบัติทางห้องปฏิบัติการเพื่อความปลอดภัยของผู้ป่วย การจัดการกับความเสี่ยงทางห้องปฏิบัติการคลินิก การพัฒนาคุณภาพเพื่อการดูแลรักษาผู้ป่วยที่ดียิ่งขึ้น วัฒนธรรมความปลอดภัยของผู้ป่วย",
    "courseDescEn":
      "Definition of patient safety; policy and goals for patient safety at global and country levels, Essential human factors for patient safety; collaboration of inter-professional team for patient care; laboratory practices for patient safety; risk management in clinical laboratory;  quality improvement for better patient care; patient safety culture.",
    "genEdType": "SC",
    "__typename": "Course",
    "dropbox": "",
  },
  "2746292": {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "2746292",
    "abbrName": "EDU SUS DEV",
    "courseNameTh": "การศึกษาเพื่อการพัฒนาที่ยั่งยืน",
    "courseNameEn": "EDUCATION FOR SUSTAINABLE DEVELOPMENT",
    "faculty": "27",
    "department": "สาขาวิชาพัฒนศึกษา",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 1.0 HR + DISC 2.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "ความรู้ ความเข้าใจในสังคมไทยและสังคมโลกเพื่อการรู้เท่าทันการเปลี่ยนแปลง อย่างมีสํานึกสากล ที่สอดคล้อง กับกระบวนทัศน์การพัฒนา การคิดและวิเคราะห์เชิงระบบในประเด็นและปัญหาที่เกิดขึ้น เป็นผู้ประกอบการที่ตระหนักรู้และ ความเข้าใจในแนวทางการพัฒนาที่ยั่งยืน การเสนอทางเลือกการพัฒนาตามปรัชญาของเศรษฐกิจพอเพียงบนฐานความร่วมมือ ระดับท้องถิ่น ภูมิภาค ระดับโลก และกลยุทธ์การจัดการศึกษาเพื่อความเป็นพลเมืองตื่นรู้ ที่มีค่านิยมและคุณลักษณะ เป็นประชาธิปไตย เพื่อการเปลี่ยนผ่านและพัฒนาสังคมอย่างยั่งยืน",
    "courseDescEn":
      "Knowledge and understanding of Thai and global societies for seeing through their changes with a global mindset in line with the development paradigm; analysis and systems thinking of emerging issues; being an entrepreneur with an awareness and understandings of sustainable development; abilities to propose development alternatives according to the sufficiency economy philosophy on the basis of local, regional, and global cooperation; strategies of the educational provision for active citizens possessing democratic values and traits for the\r\ntransformation and development of sustainable societies",
    "genEdType": "SO",
    "__typename": "Course",
    "dropbox": "",
  },
  "3800250": {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "3800250",
    "abbrName": "HUMAN RELATIONS",
    "courseNameTh": "มนุษยสัมพันธ์",
    "courseNameEn": "HUMAN RELATIONS",
    "faculty": "38",
    "department": "ไม่สังกัดภาควิชา/เทียบเท่า",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": "-",
    "genEdType": "SO",
    "__typename": "Course",
    "dropbox": "",
  },
  "3800101": {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "3800101",
    "abbrName": "GENERAL PSYCHOLOGY",
    "courseNameTh": "จิตวิทยาทั่วไป",
    "courseNameEn": "GENERAL PSYCHOLOGY",
    "faculty": "38",
    "department": "ไม่สังกัดภาควิชา/เทียบเท่า",
    "credit": 3,
    "creditHours": "LECT 2.0 CR + NL23 1.0 CR(LECT 2.0 HR + LAB 2.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "ข้อมูลและวิธีการจิตวิทยา พื้นฐานสรีรภาพของพฤติกรรม การรู้สึก การรับรู้ การเรียนรู้ การจำ การคิด การตัดสินใจ แรงผลักดันพฤติกรรม การกล่อมเกลาบุคลิกภาพ พฤติกรรมเบี่ยงเบน การบำบัด และการควบคุมพฤติกรรมเบี่ยงเบน",
    "courseDescEn":
      "Data and methods of psychology; physiological foundations of behavior; feelings, perception, learning, memory, thinking, judgement, motivation,and personality adjustment, deviant behavior, theraphy and control of deviant behavior.",
    "genEdType": "SO",
    "__typename": "Course",
    "dropbox": "",
  },
  "0294456": {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "0294456",
    "abbrName": "DESIGNING LIFE",
    "courseNameTh": "ออกแบบชีวิต",
    "courseNameEn": "DESIGNING LIFE",
    "faculty": "02",
    "department": "การศึกษาทั่วไปในศตวรรษที่ 21 หมวดสังคมศาสตร์",
    "credit": 3,
    "creditHours":
      "LECT 1.0 CR + NL23 2.0 CR (S/U)(LECT 1.0 HR + PRAC 2.0 HR + IDPS 3.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "ความเชื่อเกี่ยวกับงานและชีวิต การออกแบบชีวิตและทัศนคติของนักออกแบบ การเข้าใจตนเอง การตั้งคําถามที่ดีเพื่อ ออกแบบชีวิต การออกแบบผังชีวิต การเลือกและความสุข การสร้างต้นแบบ การทดลอง ความล้มเหลวเพื่อการเรียนรู้ การสร้าง เครือข่ายและทีม",
    "courseDescEn":
      "Beliefs about work and life; life.designing and a designer's. attitude: self-understanding; defining the issues; designing a life plan; choices and happiness; creating a prototype; test, failure for learning networking and building a team.",
    "genEdType": "SO",
    "__typename": "Course",
    "dropbox": "",
  },
  "2737201": {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "2737201",
    "abbrName": "MUSIC FOR ESTHE",
    "courseNameTh": "กิจกรรมดนตรีเพื่อสุนทรียภาพ",
    "courseNameEn": "MUSIC FOR ESTHETIC",
    "faculty": "27",
    "department": "สาขาวิชาดนตรีศึกษา",
    "credit": 3,
    "creditHours": "LECT 3.0 CR (S/U)(LECT 3.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "ดนตรีกับการพัฒนามนุษย์ หลักการปฏิบัติดนตรี ความซาบซึ้งและการแสดงออกทางดนตรี ทักษะพื้นฐาน ทางดนตรี",
    "courseDescEn":
      "Music and human development; principles of musical practices; music appreciation and expression; basic music skills.",
    "genEdType": "SO",
    "__typename": "Course",
    "dropbox": "",
  },
  "3501224": {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "3501224",
    "abbrName": "HISTORY THAI ART",
    "courseNameTh": "ประวัติศิลปะไทย",
    "courseNameEn": "HISTORY OF THAI ART",
    "faculty": "35",
    "department": "ภาควิชาทัศนศิลป์",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "PRER 3501120",
    "courseDescTh":
      "ศึกษาและวิเคราะห์วิวัฒนาการของศิลปะไทย ทั้งด้านจิตรกรรม ประติมากรรม สถาปัตยกรรม หัตถกรรม และงานศิลปะอื่นให้รู้ถึงรูปแบบ ลักษณะเฉพาะคุณค่าของศิลปะไทย ตลอดจนอิทธิพลและผลกระทบของศิลปะจากประเทศใกล้เคียงในภูมิภาคเอเชียตะวันออกเฉียงใต้",
    "courseDescEn":
      "Study and analysis of the development of painting sculpture, architecture, crafts, and other forms of Thai art, emphasizing design, characteristics and Thai art value, including influences on Southeast Asian art.",
    "genEdType": "HU",
    "__typename": "Course",
    "dropbox": "",
  },
  "0123104": {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "0123104",
    "abbrName": "UNIV THAI READING",
    "courseNameTh": "การอ่านภาษาไทยระดับอุดมศึกษา",
    "courseNameEn": "UNIVERSITY LEVEL OF THAI READING",
    "faculty": "01",
    "department": "สถาบันภาษาไทยสิรินธร",
    "credit": 3,
    "creditHours": "LECT 1.0 CR + NL23 2.0 CR(LECT 1.0 HR + PRAC 4.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "หลักการอ่าน ระดับของการอ่าน การจับใจความ การตีความบทอ่านประเภทต่างๆ ทั้งบทอ่านทั่วไป บทอ่านเชิงวิชาการ ตาราวง แผนภูมิ หรือรูปภาพ",
    "courseDescEn":
      "Reading principles; levels of reading; main idea finding; interpretation of general texts, academic texts, tables, figures and illustrations",
    "genEdType": "HU",
    "__typename": "Course",
    "dropbox": "",
  },
  "3501217": {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "3501217",
    "abbrName": "EAR MOD ART",
    "courseNameTh": "ศิลปะยุคต้นสมัยใหม่",
    "courseNameEn": "EARLY MODERN ART (15TH-17TH CENTURIES)",
    "faculty": "35",
    "department": "ภาควิชาทัศนศิลป์",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "ผลงานศิลปะตะวันตกในยุคต้นสมัยใหม่ตั้งแต่คริสต์ศตวรรษที่ 15-17 ที่มีเนื้อหาเกี่ยวกับศาสนาโดยเฉพาะพระคัมภีร์ใหม่และตำนานเกี่ยวกับเทพและบุคคลสำคัญในสมัยกรีก-โรมันโบราณ เน้นงานจิตรกรรมและประติมากรรมที่สร้างในทวีปยุโรป",
    "courseDescEn":
      "Western art objects in the early modern period from the 15th-17th centuries as related to religion, particularly the new testament and myths about important gods, goddesses and people of ancient Greece and Rome; focusing on paintings and sculptures created in Europe.",
    "genEdType": "HU",
    "__typename": "Course",
    "dropbox": "",
  },
  "2207203": {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "2207203",
    "abbrName": "PHILOS/FILMS",
    "courseNameTh": "ปรัชญากับภาพยนตร์",
    "courseNameEn": "PHILOSOPHY AND FILMS",
    "faculty": "22",
    "department": "ภาควิชาปรัชญา",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 2.0 HR + DISC 1.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "แนวคิด ข้อโต้แย้งทางปรัชญา และประเด็นทางจริยธรรมในชีวิตร่วมสมัยซึ่งนำเสนอในภาพยนตร์",
    "courseDescEn":
      "Concepts, philosophical arguments and ethical issues in contemporary life as depicted in films.",
    "genEdType": "HU",
    "__typename": "Course",
    "dropbox": "",
  },
  "3501120": {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "3501120",
    "abbrName": "HIST WEST ART I",
    "courseNameTh": "ประวัติศิลปะตะวันตก 1",
    "courseNameEn": "HISTORY OF WESTERN ART I",
    "faculty": "35",
    "department": "ภาควิชาทัศนศิลป์",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "ศึกษาและวิเคราะห์วิวัฒนาการในงานจิตรกรรม ประติมากรรม สถาปัตยกรรม และงานศิลปกรรมอื่นๆ ตั้งแต่สมัยก่อนประวัติศาสตร์ จนถึงสมัยจนตนิยมของอารยธรรมตะวันตก เน้นถึงอิทธิพลของประวัติศาสตร์ การเมือง สังคม ปรัชญา และศาสนา ที่มีต่อศิลปะตะวันตก",
    "courseDescEn":
      "Study and analysis of the development of painting, sculpture, architecture and other works of art dating from the pre-historic period to the Romantic age in western civilization, emphasizing the historical, political, social, philosophical, and religious influences on western art.",
    "genEdType": "HU",
    "__typename": "Course",
    "dropbox": "",
  },
  "0295103": {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "0295103",
    "abbrName": "LRNG LIFE",
    "courseNameTh": "การเรียนรู้เพื่อชีวิต",
    "courseNameEn": "LEARNING FOR LIFE",
    "faculty": "02",
    "department": "การศึกษาทั่วไปในศตวรรษที่ 21 หมวดสหศาสตร์",
    "credit": 3,
    "creditHours": "LECT 3.0 CR (S/U)(DISC 1.0 HR + SMNA 2.0 HR) Year Course",
    "courseCondition": "-",
    "courseDescTh":
      "การวิเคราะห์ความต้องการการพัฒนาตนเอง การวางแผนการพัฒนาตนเอง การฝึกปฏิบัติการสะท้อนคิด การ สร้างแฟ้มสะสมงานรายบุคคลด้วยการเรียนรู้ผ่านกิจกรรมเสริมหลักสูตรเชิงบูรณาการด้านคุณค่าของ จุฬาฯ",
    "courseDescEn":
      "Analysis of personal development needs; personal development plan; reflective practice developing personal portfolio through Chulalongkorn University Value Integration Programme (CUVIP).",
    "genEdType": "IN",
    "__typename": "Course",
    "dropbox": "",
  },
  "2750178": {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "2750178",
    "abbrName": "LLL",
    "courseNameTh": "การเรียนรู้ตลอดชีวิต",
    "courseNameEn": "LIFELONG LEARNING",
    "faculty": "27",
    "department": "สาขาวิชาการศึกษานอกระบบโรงเรียน",
    "credit": 3,
    "creditHours": "LECT 1.0 CR + NL23 2.0 CR(LECT 1.0 HR + PRAC 4.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "ระบบการเรียนรู้ของแต่ละบุคคลในบริบทการศึกษาตลอดชีวิต คุณลักษณะและทักษะที่จำเป็นสำหรับการเป็นบุคคลผู้มีความรักในการเรียนรู้ตลอดชีวิตโดยใช้แหล่งเรียนรู้ในวิถีชีวิตประจำวัน",
    "courseDescEn":
      "Learning system of each individual within the context of lifelong education; essential attributes and skills for becoming a person with love of lifelong learning; practical approaches for the fostering of a person with love of lifelong learning.",
    "genEdType": "IN",
    "__typename": "Course",
    "dropbox": "",
  },
  "3000106": {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "3000106",
    "abbrName": "DR/SOC",
    "courseNameTh": "แพทย์กับสังคม",
    "courseNameEn": "DOCTOR AND SOCIETY",
    "faculty": "30",
    "department": "ไม่สังกัดภาควิชา/เทียบเท่า",
    "credit": 2,
    "creditHours": "LECT 1.0 CR + NL23 1.0 CR(LECT 1.0 HR + PRAC 2.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "ประวัติศาสตร์การแพทย์ บทบาทและหน้าที่ของแพทย์ การศึกษาแพทยศาสตร์ การสืบค้นข้อมูลทางการแพทย์ การคิดเชิงวิพากย์ การสื่อสาร การเรียนและการทำงานเป็นกลุ่ม การเป็นผู้นำ การพัฒนาบุคลิกภาพ กฎหมาย จรรยาบรรณและธรรมะแห่งวิชาชีพ โครงสร้างสังคม วัฒนธรรมและประเพณีไทย สุขภาพและระบบสุขภาพ การแพทย์แผนไทยและภูมิปัญญาท้องถิ่นไทย หลักการดูแลผู้ป่วยแบบองค์รวมและประสบการณ์ในชุมชน",
    "courseDescEn":
      "History of medicine; doctor's roles and functions; medical education;\r\ninformation searching in medicine; critical thinking; communication;\r\nlearning and working as a group; leadership; personality development;\r\nprofessional laws, code of conduct and Dharma; Thai society structure, culture and tradition; health and health system; Thai traditional medicine and Thai folk wisdom; principle of holistic care and \r\ncommunity experience.",
    "genEdType": "IN",
    "__typename": "Course",
    "dropbox": "",
  },
  "0201141": {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "0201141",
    "abbrName": "COAST ENV",
    "courseNameTh": "สภาวะแวดล้อมชายฝั่งทะเล",
    "courseNameEn": "COASTAL ENVIRONMENT",
    "faculty": "02",
    "department": "ศูนย์การศึกษาทั่วไป",
    "credit": 3,
    "creditHours":
      "LECT 2.0 CR + NL36 1.0 CR(LECT 1.0 HR + DISC 1.0 HR + FWK 3.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "ความหมาย คุณค่าและความสำคัญของสภาพแวดล้อมชายฝั่งทะเล การใช้ประโยชน์จากกฎหมายและข้อกำหนดเกี่ยวกับสภาพแวดล้อมชายฝั่งทะเล ปัญหาสภาพแวดล้อมชายฝั่งทะเลอันเนื่องมาจากกิจกรรมของมนุษย์และภัยธรรมชาติ การประเมินผลกระทบสภาพแวดล้อมชายฝั่งทะเล กรณีศึกษาและการศึกษานอกสถานที่เกี่ยวกับอุตสาหกรรมชายฝั่ง การขนส่งทางทะเล ชุมชนชายฝั่งทะเล การกัดเซาะชายฝั่งและสึนามิ",
    "courseDescEn":
      "Meaning; value and importance of coastal environment; use of law and regulations of coastal environment; coastal environmental problems from human activities and natural disaster; coastal Environmental Impacts Assessment (EIA); case studies and field excursion on coastal industry, marine transportation, coastal community; coastal erosion and tsunami.",
    "genEdType": "IN",
    "__typename": "Course",
    "dropbox": "",
  },
  "0201107": {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "0201107",
    "abbrName": "LRN STUD ACT",
    "courseNameTh": "การเรียนรู้ผ่านกิจกรรมนิสิต",
    "courseNameEn": "LEARNING THROUGH STUDENT ACTIVITIES",
    "faculty": "02",
    "department": "ศูนย์การศึกษาทั่วไป",
    "credit": 3,
    "creditHours": "LECT 1.0 CR + NL36 2.0 CR(LECT 1.0 HR + FWK 6.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "แนวคิด จุดหมาย และความสำคัญของการทำกิจกรรมนิสิต กระบวนการแสวงหาและสังเคราะห์ความรู้อย่างเป็นระบบจากแหล่งความรู้ต่าง ๆ รวมทั้งกิจกรรมนิสิต การออกแบบโครงงาน วางแผน จัดทำงบประมาณ และประเมินผลโครงการ การดำเนินงาน ประเมินผลการดำเนินงาน และนำเสนอการดำเนินงานกิจกรรมนิสิต",
    "courseDescEn":
      "Concept, goal and advantages of student activities; process of seeking and synthesizing knowledge from various sources including from student activities; project design, planning, budgeting and evaluation; implementation, evaluation and presentation of projects on student activities",
    "genEdType": "IN",
    "__typename": "Course",
    "dropbox": "",
  },
};
