import React from "react";
const dataSemester = [
  {
    year: 1,
    semester: 1,
    dropbox: {
      "1": "3404117",
      "2": "0123101",
      "3": "5500111",
      "4": "2601112",
      "5": "2940104",
      "6": null,
      "7": "2945111",
      "8": null,
      "9": null,
    },
  },
  {
    year: 1,
    semester: 2,
    dropbox: {
      "1": "2400104",
      "2": null,
      "3": "5500112",
      "4": null,
      "5": "2940203",
      "6": "2940204",
      "7": "2945112",
      "8": null,
      "9": null,
    },
  },
  {
    year: 2,
    semester: 1,
    dropbox: {
      "1": null,
      "2": null,
      "3": "5500235",
      "4": "2941103",
      "5": "2940308",
      "6": "2940309",
      "7": "2945113",
      "8": null,
      "9": null,
    },
  },
  {
    year: 2,
    semester: 2,
    dropbox: {
      "1": "xxxxxxx",
      "2": "xxxxxxx",
      "3": "5500236",
      "4": null,
      "5": null,
      "6": null,
      "7": "2945310",
      "8": "xxxxxxx",
      "9": "xxxxxxx",
    },
  },
  {
    year: 3,
    semester: 1,
    dropbox: {
      "1": "xxxxxxx",
      "2": null,
      "3": "5500333",
      "4": "2941312",
      "5": null,
      "6": null,
      "7": "2945351",
      "8": "xxxxxxx",
      "9": "xxxxxxx",
    },
  },
  {
    year: 3,
    semester: 2,
    dropbox: {
      "1": "xxxxxxx",
      "2": "xxxxxxx",
      "3": null,
      "4": null,
      "5": "2941313",
      "6": "2900306",
      "7": null,
      "8": "xxxxxxx",
      "9": "xxxxxxx",
    },
  },
  {
    year: 4,
    semester: 1,
    dropbox: {
      "1": "xxxxxxx",
      "2": "xxxxxxx",
      "3": null,
      "4": null,
      "5": null,
      "6": "2941409",
      "7": null,
      "8": "xxxxxxx",
      "9": "xxxxxxx",
    },
  },
  {
    year: 4,
    semester: 2,
    dropbox: {
      "1": null,
      "2": null,
      "3": null,
      "4": null,
      "5": null,
      "6": "2900410",
      "7": null,
      "8": "xxxxxxx",
      "9": null,
    },
  },
];

const dataCourse = [
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "3404117",
    "abbrName": "INTRO TO LAW",
    "courseNameTh": "ความรู้เบื้องต้นเกี่ยวกับกฎหมายทั่วไป",
    "courseNameEn": "INTRODUCTION TO LAW",
    "faculty": "34",
    "department": "ภาควิชากฎหมายการปกครองและกฎหมายทั่วไป",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "-",
    "courseDescTh": null,
    "courseDescEn":
      "Introduction to the study of laws; nature and sources of law, kinds and characteristics of law; the making, application, and interpretation of law and its abrogation; law of persons: natural and juristic persons; legal rights; nature and kinds of rights; rights under the Civil and Commercial Codes; other laws having economic implication, including antitrust laws and consumer protection law. (Designed for students of Arts)",
    "genEdType": "SO",
    "__typename": "Course",
    "dropbox": "111",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "0123101",
    "abbrName": "PARAGRAP WRITING",
    "courseNameTh": "การเขียนย่อหน้า",
    "courseNameEn": "PARAGRAPH WRITING",
    "faculty": "01",
    "department": "สถาบันภาษาไทยสิรินธร",
    "credit": 3,
    "creditHours": "LECT 1.0 CR + NL23 2.0 CR(LECT 1.0 HR + PRAC 4.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "การเรียงลำดับความคิดในการเขียนย่อหน้า การเลือกศัพท์ คำเชื่อม และวลีที่เหมาะสม การใช้ภาษาที่เหมาะสมกับจุดประสงค์ในการเขียนและระดับของผู้อ่าน",
    "courseDescEn":
      "Organizing ideas in paragraph writing; selecting appropriate vocabulary, connectives and phrases; using Thai language appropriate for writing objectives and readers' abilities",
    "genEdType": "HU",
    "__typename": "Course",
    "dropbox": "112",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "5500111",
    "abbrName": "EXP ENG I",
    "courseNameTh": "ภาษาอังกฤษเพื่อการเรียนรู้ในชีวิตจริง 1",
    "courseNameEn": "EXPERIENTIAL ENGLISH I",
    "faculty": "55",
    "department": "ไม่สังกัดภาควิชา/เทียบเท่า",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "การฝึกทักษะทางภาษาทั้ง 4 ทักษะ เพื่อการสื่อสารในชีวิตประจำวัน การเปรียบเทียบ วิเคราะห์ และสังเคราะห์ ข้อมูลจากแหล่งต่าง ๆ และการนำเสนอประเด็นสำคัญด้วยวาจา และ/หรือเป็นลายลักษณ์อักษร",
    "courseDescEn":
      "Practice in the four language skills for everyday communication; comparing, analyzing, and synthesizing information from different sources; giving oral and/or written presentations.",
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "113",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "2601112",
    "abbrName": "INTRO FIN ACCTG",
    "courseNameTh": "การบัญชีการเงินเบื้องต้น",
    "courseNameEn": "INTRODUCTION TO FINANCIAL ACCOUNTING",
    "faculty": "26",
    "department": "ภาควิชาการบัญชี",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "ประเภทของธุรกิจ แนวคิดพื้นฐานของการบัญชี ประโยชน์ของข้อมูลทางการบัญชี การอ่านงบการเงินของกิจการให้บริการ ซื้อขายสินค้า และผลิตสินค้า การวิเคราะห์งบการเงินเบื้องต้น กระบวนการทางการบัญชี การอ่านและวิเคราะห์งบ กระแสเงินสด ภาษีธุรกิจเบื้องต้น การใช้สารสนเทศทางการบัญชีเพื่อการวางแผน ควบคุมและตัดสินใจ",
    "courseDescEn":
      "Types of business; basic concepts of accounting; usefulness of accounting data; understanding of financial statements of servicing, merchandising and manufacturing firms; introduction to financial statement analysis; accounting process; understanding and analysis of cash flow statement; introduction to business tax; use of accounting information for planning, control and decision making.",
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "114",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "2940104",
    "abbrName": "INTRO ECON",
    "courseNameTh": "เศรษฐศาสตร์เบื้องต้น",
    "courseNameEn": "INTRODUCTION TO ECONOMICS",
    "faculty": "29",
    "department": "รายวิชาหลักและทฤษฏีเศรษฐศาสตร์",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "แก่นแท้ของเศรษฐศาสตร์  เศรษฐศาสตร์เป็นศาสตร์หรือศิลป์   สภาพสังคมเศรษฐกิจตามแนวทฤษฎี   ลักษณะโครงสร้างของตลาด  มิติเวลากับความสำคัญทางเศรษฐศาสตร์  เศรษฐศาสตร์ทุนนิยมถูกกระตุ้นโดยกิเลส  วิธีการบริหารความเสี่ยง  ดุลยภาพและเสถียรภาพ   แนวคิดสำนักคลาสสิกและโอคลาสสิก   จอห์น เมย์นาร์ด เคนส์   กฎเหล็กของทฤษฎีอุปสงค์  สมการการผลิต  บทบาทของรัฐบาลในสังคมเศรษฐกิจ   การเชื่อมต่อสู่ต่างประเทศ  บัญชีประชาชาติ",
    "courseDescEn":
      "Fundamental economic concepts;  Is economics an art or a science?;  an economic society in accordance to theories;  the market structures;  time and importance in  economics;  Capitalistic economics stimulated by greed;  how to manage risk in economics;  equilibrium and stability;  fundamentals of classical schools and neo-classical schools;  John Maynard Keynes;  the iron laws of demand theory;  production function;  the role of a government in economic society;  linkage to the international community; national income accounts.",
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "115",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "2945111",
    "abbrName": "MATH ECONOMIST I",
    "courseNameTh": "คณิตศาสตร์สำหรับนักเศรษฐศาสตร์ 1",
    "courseNameEn": "MATHEMATICS FOR ECONOMISTS I",
    "faculty": "29",
    "department": "สาขาวิชาเศรษฐศาสตร์ปริมาณวิเคราะห์",
    "credit": 4,
    "creditHours": "LECT 3.0 CR + NL23 1.0 CR(LECT 3.0 HR + TUT 2.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "การประยุกต์ความรู้ทางคณิตศาสตร์กับวิชาทางเศรษฐศาสตร์ในหัวข้อต่อไปนี้ เซต สมการ และอสมการ ความสัมพันธ์ ฟังก์ชันและกราฟ ฟังก์ชันรูปแบบต่างๆ การคิดดอกเบี้ย ค่าปัจจุบัน ค่าอนาคต รวมทั้งค่ารายปี ลิมิตและความต่อเนื่อง ลำดับและอนุกรม อนุพันธ์กรณีตัวแปรเดียว การหาค่าสูงสุดและต่ำสุดของฟังก์ชันที่มีตัวแปรหนึ่งตัว ระบบสมการ เมทริกซ์อัลจีบรา",
    "courseDescEn": null,
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "117",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "2400104",
    "abbrName": "POL GOVT THAI",
    "courseNameTh": "การเมืองและการปกครองของไทย",
    "courseNameEn": "POLITICS AND GOVERNMENT OF THAILAND",
    "faculty": "24",
    "department": "ไม่สังกัดภาควิชา/เทียบเท่า",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "วิวัฒนาการของการเมืองการปกครองของไทย การเติบโตของพลังประชาธิปไตย การขยายตัวของระบบราชการในบริบทของการเปลี่ยนแปลงทางเศรษฐกิจ ปัญหาต่างๆ ในด้านการเมือง การปกครองของไทย ได้แก่ ความไร้เสถียรภาพของรัฐบาล การรวมอำนาจในการบริหารรัฐธรรมนูญ พรรคการเมือง และระบบรัฐสภา การเลือกตั้ง อำนาจนิยมในระบบการเมือง การปกครอง และการเมืองนอกรัฐสภา",
    "courseDescEn":
      "Evolution of Thai politics and government; the growth of democratic forces; expansion of public bureaucracy in the context of economic changes; various issues in Thai politics and government: instability of government, administrative centralization, constitution, political parties and parliamentary system, election, authoritarianism in Thai political system and government, ex-parliamentary politics.",
    "genEdType": "SO",
    "__typename": "Course",
    "dropbox": "121",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "5500112",
    "abbrName": "EXP ENG II",
    "courseNameTh": "ภาษาอังกฤษเพื่อการเรียนรู้ในชีวิตจริง 2",
    "courseNameEn": "EXPERIENTIAL ENGLISH II",
    "faculty": "55",
    "department": "ไม่สังกัดภาควิชา/เทียบเท่า",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "PRER 5500111",
    "courseDescTh":
      "ฝึกทักษะทางภาษาทั้ง 4 ทักษะ (ฟัง พูด อ่าน เขียน) เพิ่มเติมเพื่อการสื่อสารในชีวิตประจำวัน การวิเคราะห์ สังเคราะห์ สรุป และประเมินข้อมูลจากแหล่งต่าง ๆ และการนำเสนอประเด็นสำคัญด้วยวาจา และ/หรือเป็นลายลักษณ์อักษร",
    "courseDescEn":
      "Further practice in the four language skills for everyday communication; analyzing, synthesizing, summarizing and evaluating information from different sources; giving oral and/or written presentations.",
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "123",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "2940203",
    "abbrName": "MICROECON THEO I",
    "courseNameTh": "ทฤษฎีเศรษฐศาสตร์จุลภาค 1",
    "courseNameEn": "MICROECONOMIC THEORY I",
    "faculty": "29",
    "department": "รายวิชาหลักและทฤษฏีเศรษฐศาสตร์",
    "credit": 4,
    "creditHours": "LECT 3.0 CR + NL23 1.0 CR(LECT 3.0 HR + TUT 2.0 HR)",
    "courseCondition": "PRER 2940104 AND 2945111",
    "courseDescTh":
      "พฤติกรรมผู้บริโภค อุปสงค์และความยืดหยุ่น อุปสงค์ของตลาด พฤติกรรมผู้ผลิต ทฤษฎีต้นทุนการผลิต การกำหนดราคาและปริมาณการผลิตสินค้าของผู้ผลิตในตลาดกับลักษณะต่างๆ คือ ตลาดแข่งขันสมบูรณ์ ตลาดผูกขาด ตลาดผู้ขายน้อยราย และตลาดกึ่งแข่งขันกึ่งผูกขาด",
    "courseDescEn":
      "Consumers's theory; demand and elasticity, market demand; production Function; Cost theory; Price and output determination under perfect competition, monopoly, oligopoly, and monopolistic competition.",
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "125",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "2940204",
    "abbrName": "MACROECON THEO I",
    "courseNameTh": "ทฤษฎีเศรษฐศาสตร์มหภาค 1",
    "courseNameEn": "MACROECONOMIC THEORY I",
    "faculty": "29",
    "department": "รายวิชาหลักและทฤษฏีเศรษฐศาสตร์",
    "credit": 4,
    "creditHours": "LECT 3.0 CR + NL23 1.0 CR(LECT 3.0 HR + TUT 2.0 HR)",
    "courseCondition": "PRER 2940104 AND 2945111",
    "courseDescTh":
      "การวิเคราะห์บัญชีรายได้ประชาชาติ อุปสงค์อุปทานรวม ตลาดแรงงาน ตลาดการเงิน ตลาดทุน การวิเคราะห์ระบบเศรษฐกิจ แบบเปิดซึ่งครอบคลุมบัญชีดุลการชำระเงินระหว่างประเทศ และตลาดแลกเปลี่ยนเงินตราระหว่างประเทศ",
    "courseDescEn": null,
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "126",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "2945112",
    "abbrName": "MATH ECONOMIST II",
    "courseNameTh": "คณิตศาสตร์สำหรับนักเศรษฐศาสตร์ 2",
    "courseNameEn": "MATHEMATICS FOR ECONOMISTS II",
    "faculty": "29",
    "department": "สาขาวิชาเศรษฐศาสตร์ปริมาณวิเคราะห์",
    "credit": 4,
    "creditHours": "LECT 3.0 CR + NL23 1.0 CR(LECT 3.0 HR + TUT 2.0 HR)",
    "courseCondition": "PRER 2945111",
    "courseDescTh":
      "การประยุกต์เครื่องมือทางคณิตศาสตร์กับวิชาทางเศรษฐศาสตร์ในหัวข้อต่อไปนี้ อนุพันธ์ การหาค่าสูงสุดและต่ำสุดของฟังก์ชันที่มีหลายตัวแปร การหาค่าสูงสุดและต่ำสุดแบบมีข้อจำกัด การอินทิเกรตฟังก์ชัน อินทิกรัลที่มีค่าจำกัดและไม่จำกัด อินทิกรัลหลายชั้น ความรู้เบื้องต้นเกี่ยวกับสมการการอนุพันธ์ และสมการผลต่าง",
    "courseDescEn": null,
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "127",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "5500235",
    "abbrName": "ENG ECON",
    "courseNameTh": "ภาษาอังกฤษสำหรับเศรษฐศาสตร์",
    "courseNameEn": "ENGLISH FOR ECONOMICS",
    "faculty": "55",
    "department": "ไม่สังกัดภาควิชา/เทียบเท่า",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "PRER 5500112",
    "courseDescTh": "ฝึกทักษะการอ่านและการเขียนเกี่ยวกับหัวข้อทางเศรษฐศาสตร์",
    "courseDescEn": "Practice in reading and writing on economic topics.",
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "213",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "2941103",
    "abbrName": "INTR CUR THAI ECON",
    "courseNameTh": "ประเด็นที่เกี่ยวกับเศรษฐกิจไทยในปัจจุบันเบื้องต้น",
    "courseNameEn": "INTRODUCTION TO CURRENT ISSUES IN THE THAI ECONOMY",
    "faculty": "29",
    "department": "สาขาวิชาเศรษฐศาสตร์พัฒนาการ",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "PRER 2940104",
    "courseDescTh": null,
    "courseDescEn": null,
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "214",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "2940308",
    "abbrName": "MICROECON THEO II",
    "courseNameTh": "ทฤษฎีเศรษฐศาสตร์จุลภาค 2",
    "courseNameEn": "MICROECONOMIC THEORY II",
    "faculty": "29",
    "department": "รายวิชาหลักและทฤษฏีเศรษฐศาสตร์",
    "credit": 4,
    "creditHours": "LECT 3.0 CR + NL23 1.0 CR(LECT 3.0 HR + TUT 2.0 HR)",
    "courseCondition": "PRER 2940203",
    "courseDescTh":
      "การวิเคราะห์ดุลยภาพทั่วไป เศรษฐสาสตร์สวัสดิการ ความล้มเหลวของระบบตลาดผลภายนอก สินค้าสาธารณ การวิเคราะห์การกำหนดราคาและปริมาณการผลิตสินค้าสาธารณะ การวิเคราะห์ตลาดกรณีที่มีเรื่องการรับรู้ข้อมูลเข้ามาเกี่ยวข้อง ทฤษฎีการบริโภคภายใต้ความเสี่ยง ทฤษฎีการบริโภคระหว่างช่วงเวลา ทฤษฎีเกม",
    "courseDescEn": null,
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "215",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "2940309",
    "abbrName": "MACROECON THEO II",
    "courseNameTh": "ทฤษฎีเศรษฐศาสตร์มหภาค 2",
    "courseNameEn": "MACROECONOMIC THEORY II",
    "faculty": "29",
    "department": "รายวิชาหลักและทฤษฏีเศรษฐศาสตร์",
    "credit": 4,
    "creditHours": "LECT 3.0 CR + NL23 1.0 CR(LECT 3.0 HR + TUT 2.0 HR)",
    "courseCondition": "PRER 2940204",
    "courseDescTh":
      "การวิเคราะห์แนวคิดหลักทั้ง 7 ทางด้านเศรษฐศาสตร์มหภาค เศรษฐศาสตร์มหภาคในลักษณะพลวัต โดยเน้นทฤษฎีเกี่ยวกับความจำเริญเติบโตทางเศรฐกิจ การวิเคราะห์ระบบเศรษฐกิจแบบเปิดเชิงลึก การประยุกต์ทฤษฎีกับเหตุการณ์ปัจจุบัน",
    "courseDescEn": null,
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "216",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "2945113",
    "abbrName": "STAT ECONOMIST",
    "courseNameTh": "สถิติสำหรับนักเศรษฐศาสตร์",
    "courseNameEn": "STATISTICS FOR ECONOMISTS",
    "faculty": "29",
    "department": "สาขาวิชาเศรษฐศาสตร์ปริมาณวิเคราะห์",
    "credit": 4,
    "creditHours": "LECT 3.0 CR + NL23 1.0 CR(LECT 3.0 HR + TUT 2.0 HR)",
    "courseCondition": "-",
    "courseDescTh":
      "การประยุกต์ความรู้ทางเศรษฐศาสตร์ในหัวข้อต่อไปนี้ ตัวแปรสุ่ม ความน่าจะป็น การแจกแจงความน่าจะเป็นของตัวแปรสุ่มชนิดไม่ต่อเนื่อง การแจกแจงปกติ การแจกแจงตัวอย่าง ทฤษฎีการประมาณค่า การทดสอบสมมติฐาน การแจกแจงไควสแคว์ การทดสอบวิธีนอนพาราเมตริก",
    "courseDescEn": null,
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "217",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "GEN-ED",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "221",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "GEN-ED",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "222",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "GEN-ED",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "311",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "GEN-ED",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "321",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "GEN-ED",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "411",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "FREE ELECTIVES",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "322",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "FREE ELECTIVES",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "412",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "ELECTIVES",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "228",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "ELECTIVES",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "229",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "ELECTIVES",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "318",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "ELECTIVES",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "319",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "ELECTIVES",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "328",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "ELECTIVES",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "329",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "ELECTIVES",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "418",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "ELECTIVES",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "419",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "xxxxxxx",
    "abbrName": "ELECTIVES",
    "courseNameTh": "-",
    "courseNameEn": "-",
    "faculty": "-",
    "department": "-",
    "credit": 3,
    "creditHours": "-",
    "courseCondition": "-",
    "courseDescTh": "-",
    "courseDescEn": null,
    "genEdType": "-",
    "__typename": "Course",
    "dropbox": "428",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "2945310",
    "abbrName": "INTRO ECONO",
    "courseNameTh": "เศรษฐมิติเบื้องต้น",
    "courseNameEn": "INTRODUCTION TO ECONOMETRICS",
    "faculty": "29",
    "department": "สาขาวิชาเศรษฐศาสตร์ปริมาณวิเคราะห์",
    "credit": 4,
    "creditHours": "LECT 3.0 CR + NL23 1.0 CR(LECT 3.0 HR + TUT 2.0 HR)",
    "courseCondition": "PRER 2945113",
    "courseDescTh":
      "ปัญหาในการวิเคระห์สมการถดถอยเชิงพหุเมื่อภาวะจริงไม่เป็นไปตามสมมติฐานเทคนิคเบื้องต้นทางเศรษฐกิจมิติที่สำคัญและใช้กันแพร่หลาย การใช้ตัวแปรดัมมี่ การประมาณความสัมพันธ์ที่มีการทิ้งช่วงเวลา และการใช้สมการตัวแบบจำลองระบบสมการไซมัลเทเนียส",
    "courseDescEn": null,
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "227",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "5500236",
    "abbrName": "ENG WRIT ECON",
    "courseNameTh": "การเขียนภาษาอังกฤษสำหรับเศรษฐศาสตร์",
    "courseNameEn": "ENGLISH WRITING FOR ECONOMICS",
    "faculty": "55",
    "department": "ไม่สังกัดภาควิชา/เทียบเท่า",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "PRER 5500235",
    "courseDescTh":
      "ทักษะการเขียนบทความและรายงานวิชาการด้านเศรษฐศาสตร์ โดยเน้นทักษะการเรียบเรียงความคิดและการใช้ถ้อยคำสำนวนและศัพท์ทางเศรษฐศาสตร์",
    "courseDescEn": "Practice in advanced writing on economic topics.",
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "223",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "5500333",
    "abbrName": "ORAL ENG COMM ECON",
    "courseNameTh": "การสนทนาภาษาอังกฤษสำหรับเศรษฐศาสตร์",
    "courseNameEn": "ORAL ENGLISH COMMUNICATION FOR ECONOMICS",
    "faculty": "55",
    "department": "ไม่สังกัดภาควิชา/เทียบเท่า",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "PRER 5500236",
    "courseDescTh":
      "ฝึกทักษะการฟัง  อภิปราย  และนำเสนอต่อที่ประชุมในหัวข้อเกี่ยวกับเศรษฐศาสตร์",
    "courseDescEn":
      "Practice in aural-oral communication skills in economic contexts including discussions and presentations.",
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "313",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "2941312",
    "abbrName": "ECON POL ANA",
    "courseNameTh": "การวิเคราะห์นโยบายเศรษฐกิจ",
    "courseNameEn": "ECONOMIC POLICY ANALYSIS",
    "faculty": "29",
    "department": "สาขาวิชาเศรษฐศาสตร์พัฒนาการ",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "PRER 2940308 AND 2940309",
    "courseDescTh": null,
    "courseDescEn": null,
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "314",
  },
  {
    "studyProgram": "S",
    "semester": "1",
    "academicYear": "2566",
    "courseNo": "2945351",
    "abbrName": "DAT ECONO WORKSHOP",
    "courseNameTh": "การวิเคราะห์ข้อมูลและปฏิบัติการทางเศรษฐมิติ",
    "courseNameEn": "DATA ANALYSIS AND ECONOMETRICS WORKSHOP",
    "faculty": "29",
    "department": "สาขาวิชาเศรษฐศาสตร์ปริมาณวิเคราะห์",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "PRER 2945310",
    "courseDescTh": null,
    "courseDescEn": null,
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "317",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "2941313",
    "abbrName": "COMM ECON",
    "courseNameTh": "การสื่อสารทางเศรษฐศาสตร์",
    "courseNameEn": "COMMUNICATIONS IN ECONOMICS",
    "faculty": "29",
    "department": "สาขาวิชาเศรษฐศาสตร์พัฒนาการ",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "PRER 2940308 AND 2940309",
    "courseDescTh": null,
    "courseDescEn": null,
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "325",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "2900306",
    "abbrName": "RES METH",
    "courseNameTh": "วิธีวิทยาการวิจัย",
    "courseNameEn": "RESEARCH METHODOLOGY",
    "faculty": "29",
    "department": "ไม่สังกัดภาควิชา/เทียบเท่า",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(LECT 3.0 HR)",
    "courseCondition": "PRER 2940308 AND 2940309 AND 2945310",
    "courseDescTh": null,
    "courseDescEn": null,
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "326",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "2941409",
    "abbrName": "FIELD SEMINAR",
    "courseNameTh": "สัมมนาภาคสนาม",
    "courseNameEn": "FIELD SEMINAR",
    "faculty": "29",
    "department": "สาขาวิชาเศรษฐศาสตร์พัฒนาการ",
    "credit": 3,
    "creditHours": "LECT 2.0 CR + NL36 1.0 CR(LECT 2.0 HR + FWK 3.0 HR)",
    "courseCondition": "PRER 2900306",
    "courseDescTh": null,
    "courseDescEn":
      "Discussion of current economic issues of Thailand and of the world related to the Thai economy; analysis or seminar on new research related to Thai economy or world economy.",
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "416",
  },
  {
    "studyProgram": "S",
    "semester": "2",
    "academicYear": "2566",
    "courseNo": "2900410",
    "abbrName": "RESEARCH PAPER",
    "courseNameTh": "ปริญญานิพนธ์",
    "courseNameEn": "RESEARCH PAPER",
    "faculty": "29",
    "department": "ไม่สังกัดภาควิชา/เทียบเท่า",
    "credit": 3,
    "creditHours": "LECT 3.0 CR(DISC 3.0 HR)",
    "courseCondition":
      "PRER 2940418,2941423,2942418,2943418,2944418,2945418,2946419,2948420,2949420",
    "courseDescTh": null,
    "courseDescEn":
      "Selection of research topics in choson field of concentration; development of stages of research; data collection and analysis, report writing.",
    "genEdType": "NO",
    "__typename": "Course",
    "dropbox": "426",
  },
];
export { dataSemester, dataCourse };
